" this vimrc has been replaced by neovim/init.vim
set tabstop=4
set sw=4
set expandtab
colorscheme koehler
set laststatus=2
set nu
filetype plugin indent on
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

autocmd BufWritePre * %s/\s\+$//e

set backup
execute "set backupext=_" . strftime("%Y-%m-%d-%H:%M:%S~")
au BufRead,BufNewFile cpanfile set filetype=perl
