
[Variables]
GPU3colorFanRpmSelect=100,250,100,220
GPU3colorFanPerSelect=255,255,255,50
GPU3fanMeasureName=HWiNFOGPU3FanRpm
GPU3fanUOM=rpm
GPU3memTotalMeasureName=HWiNFOGPU3MemMax
;; HWiNFOGPU3MemMax or HWiNFOGPU3MemMaxAMD
GPU3memUsedMeasureName=HWiNFOGPU3MemUsed
;; HWiNFOGPU3Mem or HWiNFOGPU3MemUsedAMD
GPU3colorAMDmemSelect=255,255,255,50
GPU3colorNVmemSelect=100,250,100,220

GPU3SkinLoc=SimplePerfMeters\GPU3
GPU3ConfigSkinLoc=SimplePerfMeters\GPU3\config
GPU3colorFanSelectOFF=255,255,255,50
GPU3fanDisplay=0
