
[Variables]
GPU2colorFanRpmSelect=255,255,255,50
GPU2colorFanPerSelect=255,255,255,50
GPU2fanMeasureName=HWiNFOGPU2FanRpm
GPU2fanUOM=rpm
GPU2memTotalMeasureName=HWiNFOGPU2MemMax
;; HWiNFOGPU2MemMax or HWiNFOGPU2MemMaxAMD
GPU2memUsedMeasureName=HWiNFOGPU2MemUsed
;; HWiNFOGPU2Mem or HWiNFOGPU2MemUsedAMD
GPU2colorAMDmemSelect=255,255,255,50
GPU2colorNVmemSelect=100,250,100,220

GPU2SkinLoc=SimplePerfMeters\GPU2
GPU2ConfigSkinLoc=SimplePerfMeters\GPU2\config
GPU2colorFanSelectOFF=245,80,80,220
GPU2fanDisplay=1
