
[Variables]
GPU0colorFanRpmSelect=100,250,100,220
GPU0colorFanPerSelect=255,255,255,50
GPU0fanMeasureName=HWiNFOGPU0FanRpm
GPU0fanUOM=rpm
GPU0memTotalMeasureName=HWiNFOGPU0MemMax
;; HWiNFOGPU0MemMax or HWiNFOGPU0MemMaxAMD
GPU0memUsedMeasureName=HWiNFOGPU0MemUsed
;; HWiNFOGPU0Mem or HWiNFOGPU0MemUsedAMD
GPU0colorAMDmemSelect=255,255,255,50
GPU0colorNVmemSelect=100,250,100,220

GPU0SkinLoc=SimplePerfMeters\GPU0
GPU0ConfigSkinLoc=SimplePerfMeters\GPU0\config
GPU0colorFanSelectOFF=255,255,255,50
GPU0fanDisplay=0
