
[Variables]
GPU1colorFanRpmSelect=255,255,255,50
GPU1colorFanPerSelect=100,250,100,220
GPU1fanMeasureName=HWiNFOGPU1FanPer
GPU1fanUOM=%
GPU1memTotalMeasureName=HWiNFOGPU1MemMax
;; HWiNFOGPU1MemMax or HWiNFOGPU1MemMaxAMD
GPU1memUsedMeasureName=HWiNFOGPU1MemUsed
;; HWiNFOGPU1Mem or HWiNFOGPU1MemUsedAMD
GPU1colorAMDmemSelect=255,255,255,50
GPU1colorNVmemSelect=100,250,100,220

GPU1SkinLoc=SimplePerfMeters\GPU1
GPU1ConfigSkinLoc=SimplePerfMeters\GPU1\config
GPU1colorFanSelectOFF=255,255,255,50
GPU1fanDisplay=0
